// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package pbapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PK_LOG_HEARTBEAT_CMD_LOG_HEARTBEAT int32

const (
	PK_LOG_HEARTBEAT_UNKNOWN PK_LOG_HEARTBEAT_CMD_LOG_HEARTBEAT = 0
	PK_LOG_HEARTBEAT_CMD     PK_LOG_HEARTBEAT_CMD_LOG_HEARTBEAT = 168493057
)

var PK_LOG_HEARTBEAT_CMD_LOG_HEARTBEAT_name = map[int32]string{
	0:         "UNKNOWN",
	168493057: "CMD",
}

var PK_LOG_HEARTBEAT_CMD_LOG_HEARTBEAT_value = map[string]int32{
	"UNKNOWN": 0,
	"CMD":     168493057,
}

func (x PK_LOG_HEARTBEAT_CMD_LOG_HEARTBEAT) String() string {
	return proto.EnumName(PK_LOG_HEARTBEAT_CMD_LOG_HEARTBEAT_name, int32(x))
}

func (PK_LOG_HEARTBEAT_CMD_LOG_HEARTBEAT) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0, 0}
}

type PK_LOG_INFO_REQ_CMD_LOG_INFO_REQ int32

const (
	PK_LOG_INFO_REQ_UNKNOWN PK_LOG_INFO_REQ_CMD_LOG_INFO_REQ = 0
	PK_LOG_INFO_REQ_CMD     PK_LOG_INFO_REQ_CMD_LOG_INFO_REQ = 168493057
)

var PK_LOG_INFO_REQ_CMD_LOG_INFO_REQ_name = map[int32]string{
	0:         "UNKNOWN",
	168493057: "CMD",
}

var PK_LOG_INFO_REQ_CMD_LOG_INFO_REQ_value = map[string]int32{
	"UNKNOWN": 0,
	"CMD":     168493057,
}

func (x PK_LOG_INFO_REQ_CMD_LOG_INFO_REQ) String() string {
	return proto.EnumName(PK_LOG_INFO_REQ_CMD_LOG_INFO_REQ_name, int32(x))
}

func (PK_LOG_INFO_REQ_CMD_LOG_INFO_REQ) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1, 0}
}

type PK_LOG_INFO_RSP_CMD_LOG_INFO_RSP int32

const (
	PK_LOG_INFO_RSP_UNKNOWN PK_LOG_INFO_RSP_CMD_LOG_INFO_RSP = 0
	PK_LOG_INFO_RSP_CMD     PK_LOG_INFO_RSP_CMD_LOG_INFO_RSP = 185204737
)

var PK_LOG_INFO_RSP_CMD_LOG_INFO_RSP_name = map[int32]string{
	0:         "UNKNOWN",
	185204737: "CMD",
}

var PK_LOG_INFO_RSP_CMD_LOG_INFO_RSP_value = map[string]int32{
	"UNKNOWN": 0,
	"CMD":     185204737,
}

func (x PK_LOG_INFO_RSP_CMD_LOG_INFO_RSP) String() string {
	return proto.EnumName(PK_LOG_INFO_RSP_CMD_LOG_INFO_RSP_name, int32(x))
}

func (PK_LOG_INFO_RSP_CMD_LOG_INFO_RSP) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2, 0}
}

type PK_LOG_SUBSCRIBE_REQ_CMD_LOG_SUBSCRIBE_REQ int32

const (
	PK_LOG_SUBSCRIBE_REQ_UNKNOWN PK_LOG_SUBSCRIBE_REQ_CMD_LOG_SUBSCRIBE_REQ = 0
	PK_LOG_SUBSCRIBE_REQ_CMD     PK_LOG_SUBSCRIBE_REQ_CMD_LOG_SUBSCRIBE_REQ = 168493058
)

var PK_LOG_SUBSCRIBE_REQ_CMD_LOG_SUBSCRIBE_REQ_name = map[int32]string{
	0:         "UNKNOWN",
	168493058: "CMD",
}

var PK_LOG_SUBSCRIBE_REQ_CMD_LOG_SUBSCRIBE_REQ_value = map[string]int32{
	"UNKNOWN": 0,
	"CMD":     168493058,
}

func (x PK_LOG_SUBSCRIBE_REQ_CMD_LOG_SUBSCRIBE_REQ) String() string {
	return proto.EnumName(PK_LOG_SUBSCRIBE_REQ_CMD_LOG_SUBSCRIBE_REQ_name, int32(x))
}

func (PK_LOG_SUBSCRIBE_REQ_CMD_LOG_SUBSCRIBE_REQ) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3, 0}
}

type PK_LOG_SUBSCRIBE_RSP_CMD_LOG_SUBSCRIBE_RSP int32

const (
	PK_LOG_SUBSCRIBE_RSP_UNKNOWN PK_LOG_SUBSCRIBE_RSP_CMD_LOG_SUBSCRIBE_RSP = 0
	PK_LOG_SUBSCRIBE_RSP_CMD     PK_LOG_SUBSCRIBE_RSP_CMD_LOG_SUBSCRIBE_RSP = 185204738
)

var PK_LOG_SUBSCRIBE_RSP_CMD_LOG_SUBSCRIBE_RSP_name = map[int32]string{
	0:         "UNKNOWN",
	185204738: "CMD",
}

var PK_LOG_SUBSCRIBE_RSP_CMD_LOG_SUBSCRIBE_RSP_value = map[string]int32{
	"UNKNOWN": 0,
	"CMD":     185204738,
}

func (x PK_LOG_SUBSCRIBE_RSP_CMD_LOG_SUBSCRIBE_RSP) String() string {
	return proto.EnumName(PK_LOG_SUBSCRIBE_RSP_CMD_LOG_SUBSCRIBE_RSP_name, int32(x))
}

func (PK_LOG_SUBSCRIBE_RSP_CMD_LOG_SUBSCRIBE_RSP) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4, 0}
}

type PK_LOG_PUBLISH_NOTICE_CMD_LOG_PUBLISH_NOTICE int32

const (
	PK_LOG_PUBLISH_NOTICE_UNKNOWN PK_LOG_PUBLISH_NOTICE_CMD_LOG_PUBLISH_NOTICE = 0
	PK_LOG_PUBLISH_NOTICE_CMD     PK_LOG_PUBLISH_NOTICE_CMD_LOG_PUBLISH_NOTICE = 185204739
)

var PK_LOG_PUBLISH_NOTICE_CMD_LOG_PUBLISH_NOTICE_name = map[int32]string{
	0:         "UNKNOWN",
	185204739: "CMD",
}

var PK_LOG_PUBLISH_NOTICE_CMD_LOG_PUBLISH_NOTICE_value = map[string]int32{
	"UNKNOWN": 0,
	"CMD":     185204739,
}

func (x PK_LOG_PUBLISH_NOTICE_CMD_LOG_PUBLISH_NOTICE) String() string {
	return proto.EnumName(PK_LOG_PUBLISH_NOTICE_CMD_LOG_PUBLISH_NOTICE_name, int32(x))
}

func (PK_LOG_PUBLISH_NOTICE_CMD_LOG_PUBLISH_NOTICE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5, 0}
}

// log_client --> mlog
// mlog --> log_client
type PK_LOG_HEARTBEAT struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PK_LOG_HEARTBEAT) Reset()         { *m = PK_LOG_HEARTBEAT{} }
func (m *PK_LOG_HEARTBEAT) String() string { return proto.CompactTextString(m) }
func (*PK_LOG_HEARTBEAT) ProtoMessage()    {}
func (*PK_LOG_HEARTBEAT) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *PK_LOG_HEARTBEAT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PK_LOG_HEARTBEAT.Unmarshal(m, b)
}
func (m *PK_LOG_HEARTBEAT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PK_LOG_HEARTBEAT.Marshal(b, m, deterministic)
}
func (m *PK_LOG_HEARTBEAT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PK_LOG_HEARTBEAT.Merge(m, src)
}
func (m *PK_LOG_HEARTBEAT) XXX_Size() int {
	return xxx_messageInfo_PK_LOG_HEARTBEAT.Size(m)
}
func (m *PK_LOG_HEARTBEAT) XXX_DiscardUnknown() {
	xxx_messageInfo_PK_LOG_HEARTBEAT.DiscardUnknown(m)
}

var xxx_messageInfo_PK_LOG_HEARTBEAT proto.InternalMessageInfo

func (m *PK_LOG_HEARTBEAT) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PK_LOG_HEARTBEAT) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

// log_client --> mlog
type PK_LOG_INFO_REQ struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PK_LOG_INFO_REQ) Reset()         { *m = PK_LOG_INFO_REQ{} }
func (m *PK_LOG_INFO_REQ) String() string { return proto.CompactTextString(m) }
func (*PK_LOG_INFO_REQ) ProtoMessage()    {}
func (*PK_LOG_INFO_REQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *PK_LOG_INFO_REQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PK_LOG_INFO_REQ.Unmarshal(m, b)
}
func (m *PK_LOG_INFO_REQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PK_LOG_INFO_REQ.Marshal(b, m, deterministic)
}
func (m *PK_LOG_INFO_REQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PK_LOG_INFO_REQ.Merge(m, src)
}
func (m *PK_LOG_INFO_REQ) XXX_Size() int {
	return xxx_messageInfo_PK_LOG_INFO_REQ.Size(m)
}
func (m *PK_LOG_INFO_REQ) XXX_DiscardUnknown() {
	xxx_messageInfo_PK_LOG_INFO_REQ.DiscardUnknown(m)
}

var xxx_messageInfo_PK_LOG_INFO_REQ proto.InternalMessageInfo

func (m *PK_LOG_INFO_REQ) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PK_LOG_INFO_REQ) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

// mlog --> log_client
type PK_LOG_INFO_RSP struct {
	Errmsg               string   `protobuf:"bytes,1,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	Facility             string   `protobuf:"bytes,2,opt,name=facility,proto3" json:"facility,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PK_LOG_INFO_RSP) Reset()         { *m = PK_LOG_INFO_RSP{} }
func (m *PK_LOG_INFO_RSP) String() string { return proto.CompactTextString(m) }
func (*PK_LOG_INFO_RSP) ProtoMessage()    {}
func (*PK_LOG_INFO_RSP) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *PK_LOG_INFO_RSP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PK_LOG_INFO_RSP.Unmarshal(m, b)
}
func (m *PK_LOG_INFO_RSP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PK_LOG_INFO_RSP.Marshal(b, m, deterministic)
}
func (m *PK_LOG_INFO_RSP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PK_LOG_INFO_RSP.Merge(m, src)
}
func (m *PK_LOG_INFO_RSP) XXX_Size() int {
	return xxx_messageInfo_PK_LOG_INFO_RSP.Size(m)
}
func (m *PK_LOG_INFO_RSP) XXX_DiscardUnknown() {
	xxx_messageInfo_PK_LOG_INFO_RSP.DiscardUnknown(m)
}

var xxx_messageInfo_PK_LOG_INFO_RSP proto.InternalMessageInfo

func (m *PK_LOG_INFO_RSP) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func (m *PK_LOG_INFO_RSP) GetFacility() string {
	if m != nil {
		return m.Facility
	}
	return ""
}

// log_client --> mlog
type PK_LOG_SUBSCRIBE_REQ struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	Facility             string   `protobuf:"bytes,3,opt,name=facility,proto3" json:"facility,omitempty"`
	LogAddr              string   `protobuf:"bytes,4,opt,name=logAddr,proto3" json:"logAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PK_LOG_SUBSCRIBE_REQ) Reset()         { *m = PK_LOG_SUBSCRIBE_REQ{} }
func (m *PK_LOG_SUBSCRIBE_REQ) String() string { return proto.CompactTextString(m) }
func (*PK_LOG_SUBSCRIBE_REQ) ProtoMessage()    {}
func (*PK_LOG_SUBSCRIBE_REQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *PK_LOG_SUBSCRIBE_REQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PK_LOG_SUBSCRIBE_REQ.Unmarshal(m, b)
}
func (m *PK_LOG_SUBSCRIBE_REQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PK_LOG_SUBSCRIBE_REQ.Marshal(b, m, deterministic)
}
func (m *PK_LOG_SUBSCRIBE_REQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PK_LOG_SUBSCRIBE_REQ.Merge(m, src)
}
func (m *PK_LOG_SUBSCRIBE_REQ) XXX_Size() int {
	return xxx_messageInfo_PK_LOG_SUBSCRIBE_REQ.Size(m)
}
func (m *PK_LOG_SUBSCRIBE_REQ) XXX_DiscardUnknown() {
	xxx_messageInfo_PK_LOG_SUBSCRIBE_REQ.DiscardUnknown(m)
}

var xxx_messageInfo_PK_LOG_SUBSCRIBE_REQ proto.InternalMessageInfo

func (m *PK_LOG_SUBSCRIBE_REQ) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PK_LOG_SUBSCRIBE_REQ) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *PK_LOG_SUBSCRIBE_REQ) GetFacility() string {
	if m != nil {
		return m.Facility
	}
	return ""
}

func (m *PK_LOG_SUBSCRIBE_REQ) GetLogAddr() string {
	if m != nil {
		return m.LogAddr
	}
	return ""
}

// mlog --> log_client
type PK_LOG_SUBSCRIBE_RSP struct {
	Errmsg               string   `protobuf:"bytes,1,opt,name=errmsg,proto3" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PK_LOG_SUBSCRIBE_RSP) Reset()         { *m = PK_LOG_SUBSCRIBE_RSP{} }
func (m *PK_LOG_SUBSCRIBE_RSP) String() string { return proto.CompactTextString(m) }
func (*PK_LOG_SUBSCRIBE_RSP) ProtoMessage()    {}
func (*PK_LOG_SUBSCRIBE_RSP) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *PK_LOG_SUBSCRIBE_RSP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PK_LOG_SUBSCRIBE_RSP.Unmarshal(m, b)
}
func (m *PK_LOG_SUBSCRIBE_RSP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PK_LOG_SUBSCRIBE_RSP.Marshal(b, m, deterministic)
}
func (m *PK_LOG_SUBSCRIBE_RSP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PK_LOG_SUBSCRIBE_RSP.Merge(m, src)
}
func (m *PK_LOG_SUBSCRIBE_RSP) XXX_Size() int {
	return xxx_messageInfo_PK_LOG_SUBSCRIBE_RSP.Size(m)
}
func (m *PK_LOG_SUBSCRIBE_RSP) XXX_DiscardUnknown() {
	xxx_messageInfo_PK_LOG_SUBSCRIBE_RSP.DiscardUnknown(m)
}

var xxx_messageInfo_PK_LOG_SUBSCRIBE_RSP proto.InternalMessageInfo

func (m *PK_LOG_SUBSCRIBE_RSP) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

// mlog --> log_client
type PK_LOG_PUBLISH_NOTICE struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Timestamp            string   `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level                int32    `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Pid                  int32    `protobuf:"varint,5,opt,name=pid,proto3" json:"pid,omitempty"`
	File                 string   `protobuf:"bytes,6,opt,name=file,proto3" json:"file,omitempty"`
	Funcname             string   `protobuf:"bytes,7,opt,name=funcname,proto3" json:"funcname,omitempty"`
	Line                 int32    `protobuf:"varint,8,opt,name=line,proto3" json:"line,omitempty"`
	Facility             string   `protobuf:"bytes,9,opt,name=facility,proto3" json:"facility,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PK_LOG_PUBLISH_NOTICE) Reset()         { *m = PK_LOG_PUBLISH_NOTICE{} }
func (m *PK_LOG_PUBLISH_NOTICE) String() string { return proto.CompactTextString(m) }
func (*PK_LOG_PUBLISH_NOTICE) ProtoMessage()    {}
func (*PK_LOG_PUBLISH_NOTICE) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *PK_LOG_PUBLISH_NOTICE) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PK_LOG_PUBLISH_NOTICE.Unmarshal(m, b)
}
func (m *PK_LOG_PUBLISH_NOTICE) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PK_LOG_PUBLISH_NOTICE.Marshal(b, m, deterministic)
}
func (m *PK_LOG_PUBLISH_NOTICE) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PK_LOG_PUBLISH_NOTICE.Merge(m, src)
}
func (m *PK_LOG_PUBLISH_NOTICE) XXX_Size() int {
	return xxx_messageInfo_PK_LOG_PUBLISH_NOTICE.Size(m)
}
func (m *PK_LOG_PUBLISH_NOTICE) XXX_DiscardUnknown() {
	xxx_messageInfo_PK_LOG_PUBLISH_NOTICE.DiscardUnknown(m)
}

var xxx_messageInfo_PK_LOG_PUBLISH_NOTICE proto.InternalMessageInfo

func (m *PK_LOG_PUBLISH_NOTICE) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *PK_LOG_PUBLISH_NOTICE) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *PK_LOG_PUBLISH_NOTICE) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *PK_LOG_PUBLISH_NOTICE) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *PK_LOG_PUBLISH_NOTICE) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *PK_LOG_PUBLISH_NOTICE) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *PK_LOG_PUBLISH_NOTICE) GetFuncname() string {
	if m != nil {
		return m.Funcname
	}
	return ""
}

func (m *PK_LOG_PUBLISH_NOTICE) GetLine() int32 {
	if m != nil {
		return m.Line
	}
	return 0
}

func (m *PK_LOG_PUBLISH_NOTICE) GetFacility() string {
	if m != nil {
		return m.Facility
	}
	return ""
}

func init() {
	proto.RegisterEnum("pbapi.PK_LOG_HEARTBEAT_CMD_LOG_HEARTBEAT", PK_LOG_HEARTBEAT_CMD_LOG_HEARTBEAT_name, PK_LOG_HEARTBEAT_CMD_LOG_HEARTBEAT_value)
	proto.RegisterEnum("pbapi.PK_LOG_INFO_REQ_CMD_LOG_INFO_REQ", PK_LOG_INFO_REQ_CMD_LOG_INFO_REQ_name, PK_LOG_INFO_REQ_CMD_LOG_INFO_REQ_value)
	proto.RegisterEnum("pbapi.PK_LOG_INFO_RSP_CMD_LOG_INFO_RSP", PK_LOG_INFO_RSP_CMD_LOG_INFO_RSP_name, PK_LOG_INFO_RSP_CMD_LOG_INFO_RSP_value)
	proto.RegisterEnum("pbapi.PK_LOG_SUBSCRIBE_REQ_CMD_LOG_SUBSCRIBE_REQ", PK_LOG_SUBSCRIBE_REQ_CMD_LOG_SUBSCRIBE_REQ_name, PK_LOG_SUBSCRIBE_REQ_CMD_LOG_SUBSCRIBE_REQ_value)
	proto.RegisterEnum("pbapi.PK_LOG_SUBSCRIBE_RSP_CMD_LOG_SUBSCRIBE_RSP", PK_LOG_SUBSCRIBE_RSP_CMD_LOG_SUBSCRIBE_RSP_name, PK_LOG_SUBSCRIBE_RSP_CMD_LOG_SUBSCRIBE_RSP_value)
	proto.RegisterEnum("pbapi.PK_LOG_PUBLISH_NOTICE_CMD_LOG_PUBLISH_NOTICE", PK_LOG_PUBLISH_NOTICE_CMD_LOG_PUBLISH_NOTICE_name, PK_LOG_PUBLISH_NOTICE_CMD_LOG_PUBLISH_NOTICE_value)
	proto.RegisterType((*PK_LOG_HEARTBEAT)(nil), "pbapi.PK_LOG_HEARTBEAT")
	proto.RegisterType((*PK_LOG_INFO_REQ)(nil), "pbapi.PK_LOG_INFO_REQ")
	proto.RegisterType((*PK_LOG_INFO_RSP)(nil), "pbapi.PK_LOG_INFO_RSP")
	proto.RegisterType((*PK_LOG_SUBSCRIBE_REQ)(nil), "pbapi.PK_LOG_SUBSCRIBE_REQ")
	proto.RegisterType((*PK_LOG_SUBSCRIBE_RSP)(nil), "pbapi.PK_LOG_SUBSCRIBE_RSP")
	proto.RegisterType((*PK_LOG_PUBLISH_NOTICE)(nil), "pbapi.PK_LOG_PUBLISH_NOTICE")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xcf, 0x8e, 0x9a, 0x50,
	0x14, 0x87, 0xeb, 0x1f, 0x54, 0x4e, 0x17, 0xa5, 0x37, 0x6a, 0x48, 0xd3, 0x45, 0xc3, 0xaa, 0x49,
	0x9b, 0xa6, 0x4d, 0x9f, 0x40, 0x90, 0x56, 0xa2, 0x02, 0x03, 0x9a, 0x71, 0xc7, 0xa0, 0xa0, 0x73,
	0x13, 0x10, 0x82, 0xcc, 0x4c, 0x66, 0xe7, 0x38, 0xef, 0x30, 0x4f, 0x30, 0x0b, 0x17, 0xf3, 0x90,
	0x93, 0x7b, 0xbd, 0x38, 0x81, 0x91, 0xc4, 0xdd, 0xef, 0x1c, 0xbd, 0x7c, 0xe7, 0x7e, 0x07, 0x80,
	0x77, 0x63, 0xfc, 0x2b, 0x4e, 0xa2, 0x34, 0x42, 0x5c, 0x3c, 0x77, 0x63, 0x2c, 0x2d, 0x41, 0x30,
	0x87, 0xce, 0xc8, 0xf8, 0xef, 0x0c, 0xd4, 0x9e, 0x35, 0x91, 0xd5, 0xde, 0x04, 0x21, 0xa8, 0xaf,
	0xdd, 0xd0, 0x17, 0x2b, 0xdf, 0x2a, 0xdf, 0x79, 0x8b, 0x66, 0x24, 0x40, 0x2d, 0xbe, 0xf3, 0xc4,
	0x2a, 0x6d, 0x91, 0x28, 0xfd, 0x84, 0xcf, 0xca, 0xb8, 0x5f, 0x38, 0xfa, 0x11, 0x9a, 0x53, 0x7d,
	0xa8, 0x1b, 0x97, 0xba, 0xf0, 0x01, 0x01, 0xd4, 0x94, 0x71, 0x5f, 0x78, 0xd8, 0xbe, 0x98, 0x92,
	0x07, 0x9f, 0x18, 0x47, 0xd3, 0xff, 0x19, 0x8e, 0xa5, 0x5e, 0x9c, 0x89, 0xf9, 0x01, 0x42, 0x86,
	0x39, 0x9e, 0x2c, 0xa5, 0x24, 0x05, 0x8a, 0x6d, 0xa2, 0x2e, 0x34, 0xfc, 0x24, 0x09, 0x37, 0x2b,
	0xc6, 0x61, 0x15, 0xfa, 0x02, 0xad, 0xa5, 0xbb, 0xc0, 0x01, 0x4e, 0xef, 0x19, 0xee, 0x58, 0xbf,
	0x67, 0xda, 0x66, 0x09, 0x73, 0x3f, 0x93, 0x9e, 0x2b, 0xd0, 0x66, 0x50, 0x7b, 0x2a, 0xdb, 0x8a,
	0xa5, 0xc9, 0xea, 0xf9, 0xf7, 0xcb, 0xcd, 0x51, 0xcb, 0xcf, 0x81, 0x44, 0x68, 0x06, 0xd1, 0xaa,
	0xe7, 0x79, 0x89, 0x58, 0xa7, 0x3f, 0x65, 0xa5, 0xf4, 0x1b, 0x3a, 0xd9, 0x84, 0x79, 0xe8, 0xa9,
	0x31, 0x77, 0x44, 0xcd, 0xd5, 0xa9, 0x29, 0xcb, 0xfd, 0x94, 0x10, 0x4a, 0x44, 0xec, 0x88, 0x88,
	0xa7, 0x2a, 0x74, 0x18, 0xc2, 0x9c, 0xca, 0x23, 0xcd, 0x1e, 0x38, 0xba, 0x31, 0xd1, 0x14, 0x95,
	0x98, 0xb8, 0x8e, 0x36, 0x69, 0x66, 0x82, 0x64, 0x62, 0x82, 0x40, 0x99, 0x09, 0xb2, 0x91, 0xaf,
	0xc0, 0xa7, 0x38, 0xf4, 0x37, 0xa9, 0x1b, 0xc6, 0x4c, 0xc5, 0x5b, 0x03, 0xb5, 0x81, 0x0b, 0xfc,
	0x5b, 0x3f, 0xa0, 0x26, 0x38, 0xeb, 0x50, 0x50, 0x9f, 0xd8, 0x13, 0x39, 0xda, 0x23, 0x91, 0xb0,
	0x96, 0x38, 0xf0, 0xc5, 0xc6, 0x81, 0x45, 0x32, 0x75, 0x7c, 0xb3, 0x5e, 0xd0, 0x6d, 0x34, 0x99,
	0x63, 0x56, 0x93, 0xff, 0x07, 0x78, 0xed, 0x8b, 0x2d, 0xfa, 0x08, 0x9a, 0x73, 0x3b, 0xe1, 0x0b,
	0xef, 0xc6, 0x1f, 0xe8, 0x66, 0x5e, 0x0a, 0xb7, 0x3c, 0x25, 0xe6, 0x71, 0xbb, 0x9f, 0xcd, 0x1b,
	0xf4, 0x8b, 0xfb, 0xfb, 0x1a, 0x00, 0x00, 0xff, 0xff, 0xa8, 0xc1, 0xc9, 0xc7, 0x7e, 0x03, 0x00,
	0x00,
}
